Version 0.3.1: python-colormath and 2 bugfixes
There are two main problems with using Photoshop:
- it doesn't run on Linux
- it's not open source
Apart from that, I'm not sure whether it would be possible to easily
script the color conversions I need so that I wouldn't have to do them
by hand.  But the first two reasons are enough to look for alternatives.

I have recently found a very nice library that seems to do just what I
want: python-colormath (http://github.com/gtaylor/python-colormath), so
in the last couple commits I've added scripts for automated conversion
and updating of colors in Selenized config files.

This commit updates the color values in RGB spaces with the ones
obtained with python-colormath - almost all differences are rounding
differences (+/- 1 unit - negligible), but there is one noticeable
exception: Apple RGB values for bright reds (both reds in selenized
medium and bright red in selenized black) differ significantly.  I will
have to check who is right here - Photoshop or python-colormath.

Apart from that there are two intentional changes in LAB values:
- bright white (used for emphasized foreground) in selenized medium has
  corrected lightness: it used to be 83, but the correct value is 10
  more than foreground lightness, i.e. 88.
- bright black (used for comments) in selenized black is made lighter,
  to be more similar to "medium" and "dark" versions of the palette (so
  that the difference between foreground and bright black is 15 in all
  variants).